/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/appBar.vue')['default']
    FormIframe: typeof import('./src/components/formIframe.vue')['default']
    FormsList: typeof import('./src/components/formsList.vue')['default']
    InstallPrompt: typeof import('./src/components/installPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemePicker: typeof import('./src/components/themePicker.vue')['default']
  }
}
